/**
 * Kegiatan yang sudah lewat sebelum agenda pindah ke portal, dirangkum dari
 * arsip media SWE Growth. Tambah baris
 * baru di paling atas; `month` cukup "YYYY-MM" (bulan kegiatan).
 */
export type PastActivity = { month: string; title: string; note?: string };

export const PAST_ACTIVITIES: PastActivity[] = [
  { month: '2026-09', title: 'Kopdar offline chapter Jogja' },
  { month: '2026-09', title: '1 Jam Lebih Dekat bareng Mas Ary: tech recruiter di perusahaan Eropa' },
  { month: '2026-07', title: '1 Jam Lebih Dekat bareng Mas Lino: dua dekade ngoding pakai PHP' },
  { month: '2026-07', title: 'Diskusi & sharing komunitas AI tools' },
  { month: '2026-07', title: '1 Jam Lebih Dekat bareng Mas Agung: researcher di Pusan National University' },
  { month: '2026-06', title: '1 Jam Lebih Dekat bareng Mas Ahmad Rosid: ngoding sampai tua, why not?' },
  { month: '2026-06', title: 'Diskusi komunitas: hidup sehat' },
  { month: '2026-06', title: '1 Jam Lebih Dekat bareng Kang Riandy, Founder IDN Remote' },
  { month: '2026-05', title: '1 Jam Lebih Dekat bareng Mas Ariaseta, Founder Sumopod' },
  { month: '2026-05', title: '1 Jam Kenal Tech Bro bareng Mas Tegar: tech lead di perusahaan Singapura' },
  { month: '2026-05', title: 'Kelas Menulis untuk Software Engineer — Sesi 02' },
  { month: '2026-05', title: 'Kelas Menulis untuk Software Engineer — Sesi 01' },
  { month: '2026-04', title: 'AI Tools Sync #1: diskusi grup AI' },
  { month: '2026-04', title: 'Community Talks bareng Mas Agung: tech interview sambil kuliah PhD' },
  { month: '2026-02', title: 'Belajar Bareng Computing Fundamentals' },
  { month: '2026-01', title: 'Community Talks bareng Mas Oshi: belajar dari kegagalan belasan tahun berkarir' },
  { month: '2026-01', title: 'SDLC zaman now bareng Mas Gogo' },
  { month: '2026-01', title: 'Seni komunikasi untuk software engineer' },
  { month: '2025-12', title: 'Member Space: programmer belajar UI/UX, buat apa?' },
  { month: '2025-12', title: 'Community Talks: go global dari komunitas lokal' },
  { month: '2025-12', title: 'Parenthink: raising children who outthink the machines' },
  { month: '2025-12', title: 'Monthly Mobile Assemble bareng Is a Code' },
  { month: '2025-11', title: 'Belajar bareng Rust bareng Rustacean (10 sesi)' },
  { month: '2025-11', title: 'Bahas-bahas soal CS fundamental' },
  { month: '2025-11', title: 'Member Space: mobile engineering at scale' },
  { month: '2025-11', title: 'Member Space: upgrade skill FE, mulai dari mana?' },
  { month: '2025-10', title: 'Member Space: AI coding tools buat kaum mendang-mending' },
  { month: '2025-10', title: 'Member Space: kontribusi open source & sertifikasi AWS' },
  { month: '2025-10', title: 'Managerial Forum #2' },
  { month: '2025-09', title: 'Managerial Forum' },
  { month: '2025-09', title: 'Beasiswa Upskill #1', note: '9 penerima' },
  { month: '2025-08', title: 'System design challenge: calendar app' },
  { month: '2025-08', title: 'Mentor Insight: coding, (masih) life changer di era sekarang?' },
  { month: '2025-08', title: 'Bedah buku chapter 9: refactoring' },
  { month: '2025-07', title: 'CS Fun-day-mentals (2 sesi)' },
  { month: '2025-07', title: 'Mentor Insight bareng Mas Zain Fathoni' },
  { month: '2025-07', title: 'Book club' },
  { month: '2025-07', title: 'Mentor Insight: nge-vibe coding bareng Mas Levi' },
  { month: '2025-06', title: 'CS fundamental session' },
  { month: '2025-06', title: 'Bedah buku: Software Engineering, A Modern Approach' },
  { month: '2025-06', title: 'Career growth talks bareng Kang Fahru' },
  { month: '2025-06', title: 'Career growth di tech consultant bareng Mas Doni (Zero One Group)' },
  { month: '2025-06', title: 'CS Fun-day-mentals: HackerRank & system design' },
  { month: '2025-05', title: 'Coding x content untuk software engineer' },
  { month: '2025-05', title: 'Beyond coding as software engineer' },
  { month: '2025-05', title: 'Kelas bareng mentor: System Design 101 batch #2' },
  { month: '2025-05', title: 'Ngobrol komunitas: standar software engineer jago?' },
  { month: '2025-04', title: 'Program getting job in 90 days, kok bisa?' },
  { month: '2025-02', title: 'CS Fun-day-mentals: binary search' },
  { month: '2025-02', title: 'Community Talks #2: AI coding assistant' },
  { month: '2025-02', title: 'CS Fun-day-mentals: diskusi & bahas soal' },
  { month: '2025-02', title: 'Kumpul komunitas: ngoding di plat merah' },
  { month: '2025-01', title: 'Opening of the year bareng Mas Gogo: prediksi karir software engineer' },
  { month: '2024-12', title: 'Why not, why yes kuliah S2 CS' },
  { month: '2024-12', title: 'CS Fun-day-mentals: refresh leetcode & CS fundamentals' },
  { month: '2024-11', title: 'Live podcast: tips belajar bahasa Inggris untuk software engineer' },
  { month: '2024-10', title: 'Ngobrol bareng Mas Alip: kerja dan hidup di Dubai sebagai software engineer' },
  { month: '2024-10', title: 'Indie hacker talks bareng Mas Gilang: software engineer buat produk sendiri' },
  { month: '2024-10', title: 'English Club' },
  { month: '2024-09', title: 'Cerita di balik project sprint bareng Mas Nanda' },
  { month: '2024-09', title: 'Diskusi SolidJS bareng grup FE' },
  { month: '2024-09', title: 'Ngobrol bareng Mas Gogo' },
  { month: '2024-08', title: 'System Design 101 untuk software engineer bareng Mas Panji' },
  { month: '2024-08', title: 'Mentor Insight: valuable SWE during tech winter bareng Mas Nayaka' },
  { month: '2024-08', title: 'The truth of full stack dev career bareng Mas Indra Zufli' },
  { month: '2024-08', title: 'Ngobrol bareng Cak Mul: karir IT berbagai zaman' },
];
